export const abbreviationsMapper: Record<string, string> = {
  'am.': 'ante meridiem',
  'pm.': 'post meridiem',
  'apt.': 'apartment',
  'ave.': 'avenue',
  'blvd.': 'boulevard',
  'dept.': 'department',
  'dr.': 'doctor',
  'esp.': 'especially',
  'etc.': 'et cetera',
  'ex.': 'example',
  'fig.': 'figure',
  'ft.': 'feet',
  'hrs.': 'hours',
  'inc.': 'incorporated',
  'jr.': 'junior',
  'km.': 'kilometer',
  'lb.': 'pound',
  'lit.': 'literature',
  'mfg.': 'manufacturing',
  'mr.': 'Mr.',
  'mrs.': 'Mrs.',
  'mt.': 'mountain',
  'no.': 'number',
  'oz.': 'ounce',
  'pg.': 'page',
  'pl.': 'place',
  'pt.': 'part',
  'rd.': 'road',
  'rev.': 'reverend',
  'sgt.': 'sergeant',
  'sq.': 'square',
  'sr.': 'senior',
  'st.': 'street',
  'tsp.': 'teaspoon',
  'univ.': 'university',
  'vol.': 'volume',
  'vs.': 'versus',
  'wt.': 'weight',
  'yd.': 'yard',
  'yr.': 'year',
  'co.': 'company',
  'corp.': 'corporation',
  'eg.': 'for example',
  'ie.': 'that is',
  'na.': 'not applicable',
  'po.': 'post office',
  'us.': 'united states',
  'acct.': 'account',
  'adj.': 'adjective',
  'adm.': 'administrator',
  'adv.': 'adverb',
  'agt.': 'agent',
  'appt.': 'appointment',
  'assn.': 'association',
  'attn.': 'attention',
  'atm.': 'automated teller machine',
  'bldg.': 'building',
  'bros.': 'brothers',
  'c.': 'centigrade',
  'cc.': 'carbon copy',
  'cd.': 'compact disc',
  'cfm.': 'cubic feet per minute',
  'cis.': 'computer information systems',
  'cmdr.': 'commander',
  'cnr.': 'corner',
  'comm.': 'commission',
  'comp.': 'computer',
  'condo.': 'condominium',
  'const.': 'construction',
  'coord.': 'coordinator',
  'cpa.': 'certified public accountant',
  'cpl.': 'couple',
  'cred.': 'creditor',
  'cust.': 'customer',
  'db.': 'decibel',
  'dec.': 'decimal',
  'del.': 'delivery',
  'dir.': 'director',
  'dist.': 'district',
  'div.': 'division',
  'doz.': 'dozen',
  'e.': 'east',
  'ea.': 'each',
  'ed.': 'editor',
  'emt.': 'emergency medical technician',
  'eng.': 'engineer',
  'env.': 'environmental',
  'eq.': 'equal',
  'est.': 'estimated',
  'exp.': 'export',
  'ext.': 'extension',
  'f.': 'fahrenheit',
  'fam.': 'family',
  'fax.': 'facsimile',
  'fed.': 'federal',
  'fl.': 'floor',
  'fm.': 'frequency modulation',
  'frt.': 'freight',
  'fwy.': 'freeway',
  'gal.': 'gallon',
  'gen.': 'general',
  'gov.': 'government',
  'grad.': 'graduate',
  'grp.': 'group',
  'hwy.': 'highway',
  'ibid.': 'ibidem (in the same place)',
  'insp.': 'inspector',
  'int.': 'interest',
  'inv.': 'invoice',
  'iso.': 'International Organization for Standardization',
  'jct.': 'junction',
  'kg.': 'kilogram',
  'llc.': 'limited liability company',
  'lmk.': 'let me know',
  'loc.': 'location',
  'lt.': 'lieutenant',
  'm.': 'meter',
  'mgr.': 'manager',
  'misc.': 'miscellaneous',
  'ml.': 'milliliter',
  'mm.': 'millimeter',
  'mph.': 'miles per hour',
  'nos.': 'numbers',
};

export const abbreviationsMatchPattern = new RegExp(
  `(${Object.keys(abbreviationsMapper).join('|').replace(/\./g, '\\.')})`,
  'gi',
);

export const specialCharactersMapper: Record<string, string> = {
  '%': 'percentage',
  '<': 'left arrow',
  '>': 'right arrow',
  '&': 'ampersand',
  '@': 'at',
  '#': 'hash',
  '*': 'asterisk',
  '+': 'plus',
  '-': 'minus',
  '/': 'slash',
  '\\': 'backslash',
  '|': 'pipe',
  '^': 'caret',
  '~': 'tilde',
  '(': 'left parenthesis',
  ')': 'right parenthesis',
  '{': 'left curly bracket',
  '}': 'right curly bracket',
  '[': 'left square bracket',
  ']': 'right square bracket',
  '=': 'equals',
  _: 'underscore',
};

export const symbols = [
  'pad',
  '-',
  '!',
  "'",
  '(',
  ')',
  ',',
  '.',
  ':',
  ';',
  '?',
  ' ',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
  'eos',
];
